FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

# Copy the native executable
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8081
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]