package org.folio.sidecar.service.filter;

import static org.apache.commons.lang3.StringUtils.substringBefore;
import static org.apache.commons.lang3.exception.ExceptionUtils.getRootCauseStackTrace;
import static org.folio.sidecar.utils.CollectionUtils.sortByOrder;
import static org.folio.sidecar.utils.RoutingUtils.dumpContextData;
import static org.folio.sidecar.utils.RoutingUtils.dumpHeaders;
import static org.folio.sidecar.utils.RoutingUtils.putRequestStage;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.ext.web.RoutingContext;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;
import java.util.Arrays;
import java.util.List;
import lombok.extern.log4j.Log4j2;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Log4j2
@ApplicationScoped
public class RequestFilterService {

  private final List<IngressRequestFilter> ingressRequestFilters;
  private final List<EgressRequestFilter> egressRequestFilters;
  private final boolean tracingOnError;

  @Inject
  public RequestFilterService(Instance<IngressRequestFilter> ingressRequestFilters,
    Instance<EgressRequestFilter> egressRequestFilters,
    @ConfigProperty(name = "filters.tracing.on-error", defaultValue = "false") boolean tracingOnError) {
    this.ingressRequestFilters = sortByOrder(ingressRequestFilters);
    this.egressRequestFilters = sortByOrder(egressRequestFilters);
    this.tracingOnError = tracingOnError;
  }

  public Future<RoutingContext> filterIngressRequest(RoutingContext routingContext) {
    return applyFilterChain(routingContext, ingressRequestFilters);
  }

  public Future<RoutingContext> filterEgressRequest(RoutingContext routingContext) {
    return applyFilterChain(routingContext, egressRequestFilters);
  }

  private Future<RoutingContext> applyFilterChain(RoutingContext rc, List<? extends RequestFilter> filters) {
    if (filters.isEmpty()) {
      return Future.succeededFuture(rc);
    }

    var filterFuture = applyFilter(filters.getFirst(), rc);
    for (int i = 1; i < filters.size(); i++) {
      var currentFilter = filters.get(i);
      filterFuture = filterFuture.compose(ctx -> applyFilter(currentFilter, ctx));
    }

    return !tracingOnError ? filterFuture : filterFuture.onFailure(traceContext(rc));
  }

  /**
   * Records the filter as the stage the request entered, then applies it.
   *
   * <p>The stage is the filter class name without the suffix generated by CDI ({@code _ClientProxy},
   * {@code _Subclass}). It is recorded before the filter's own skip check, so it names the last filter the request
   * entered, not necessarily the last one that did work.</p>
   *
   * @param filter filter to apply
   * @param rc routing context
   * @return result of the filter
   */
  private static Future<RoutingContext> applyFilter(RequestFilter filter, RoutingContext rc) {
    putRequestStage(rc, substringBefore(filter.getClass().getSimpleName(), "_"));
    return filter.applyFilter(rc);
  }

  private static Handler<Throwable> traceContext(RoutingContext rc) {
    return throwable -> {
      if (!log.isDebugEnabled()) {
        return;
      }

      var errorMessage = throwable.getMessage();
      var causeLocation = getCausePlace(throwable);
      log.debug("Exception happened while applying filters: error = {}, {}", errorMessage, causeLocation);

      var headersDump = dumpHeaders(rc).get();
      var contextDump = dumpContextData(rc).get();

      log.debug("""
        Current state of request context:
        ********** Headers *******************
        {}
        ********** Context Data **************
        {}
        """, headersDump, contextDump);
    };
  }

  private static String getCausePlace(Throwable throwable) {
    String[] st = getRootCauseStackTrace(throwable);
    return Arrays.stream(st).skip(1).findFirst().orElse("Unknown");
  }
}
